#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

#if test "x$XDG_CONFIG_HOME" = "x" ; then
#    export XDG_CONFIG_HOME=$HOME/.config
#fi
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
[ -d "$XDG_CONFIG_HOME"  ] || mkdir -p "$XDG_CONFIG_HOME"

export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
[ -d "$XDG_CACHE_HOME"  ] || mkdir -p "$XDG_CACHE_HOME"

export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
[ -d "$XDG_DATA_HOME"  ] || mkdir -p "$XDG_DATA_HOME"

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.config/X11/xresources
usermodmap=$HOME/.config/X11/xmodmap

sysscripts=/etc/X11/xinit/xinitrc.d
userscripts=$HOME/.config/X11/xinitrc.d

SESSION=${1:-dwm}

# merge in defaults and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs
if [ -d "$sysscripts" ] ; then
    for f in $sysscripts/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ -d "$userscripts" ] ; then
    for f in $userscripts/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f

    if [ -d "$userscripts/$SESSION" ] ; then
        for f in $userscripts/$SESSION/?*.sh ; do
            [ -x "$f" ] && . "$f"
        done
        unset f
    fi
fi

get_prog(){
	local prog=""
	case "$SESSION" in
		awesome) prog+=(awesome) ;;
		bspwm) prog+=(bspwm-session) ;;
		budgie) prog+=(budgie-desktop) ;;
		cinnamon) prog+=(cinnamon-session) ;;
		deepin) prog+=(startdde) ;;
		dwm) prog+=(dwm) ;;
		enlightenment) prog+=(enlightenment_start) ;;
		fluxbox) prog+=(startfluxbox) ;;
		gnome) prog+=(gnome-session) ;;
		i3|i3wm) prog+=(i3 --shmlog-size 0) ;;
		jwm) prog+=(jwm) ;;
		kde) prog+=(startkde) ;;
		lxde) prog+=(startlxde) ;;
		lxqt) prog+=(lxqt-session) ;;
		mate) prog+=(mate-session) ;;
		xfce) prog+=(xfce4-session) ;;
		openbox) prog+=(openbox-session) ;;
		*) prog+=("$SESSION") ;;
	esac

	echo "${prog[*]}"
}

exec $(get_prog)

# 使用下面的 dbus-launch 方式启动, 在 lightDM 下会导致 dunst 出现问题
# 1. dunst 启动成功, 但无法接收到 notify-send 的消息
# 2. 启动 dwm 后, 再手动启动 dunst 会失败, "CRITICAL: cannot connect to dbus", 需要执行 export $(dbus-launch)
# TODO: 原因待查
# get_session(){
# 	local dbus_args=(--sh-syntax --exit-with-session)
# 	case "$SESSION" in
# 		awesome) dbus_args+=(awesome) ;;
# 		bspwm) dbus_args+=(bspwm-session) ;;
# 		budgie) dbus_args+=(budgie-desktop) ;;
# 		cinnamon) dbus_args+=(cinnamon-session) ;;
# 		deepin) dbus_args+=(startdde) ;;
# 		dwm) dbus_args+=(dwm) ;;
# 		enlightenment) dbus_args+=(enlightenment_start) ;;
# 		fluxbox) dbus_args+=(startfluxbox) ;;
# 		gnome) dbus_args+=(gnome-session) ;;
# 		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
# 		jwm) dbus_args+=(jwm) ;;
# 		kde) dbus_args+=(startkde) ;;
# 		lxde) dbus_args+=(startlxde) ;;
# 		lxqt) dbus_args+=(lxqt-session) ;;
# 		mate) dbus_args+=(mate-session) ;;
# 		xfce) dbus_args+=(xfce4-session) ;;
# 		openbox) dbus_args+=(openbox-session) ;;
# 		*) dbus_args+=("$SESSION") ;;
# 	esac
# 
# 	echo "dbus-launch ${dbus_args[*]}"
# }
# 
# exec $(get_session)

# if we got here, then exec failed
exit 1
